#!/bin/bash
###
# File: grub-install
# Author: Leopold Meinel (leo@meinel.dev)
# -----
# Copyright (c) 2022 Leopold Meinel & contributors
# SPDX ID: GPL-3.0-or-later
# URL: https://www.gnu.org/licenses/gpl-3.0-standalone.html
# -----
###

set -eu

# this will
# 1) call grub-install
# 2) call grub-mkconfig
# 3) sign the bootloader
cryptboot update-grub
